name: CI - Build & Push

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ${{ secrets.AWS_REGION}}
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t ${{ env.ECR_REPOSITORY}}:${{ github.sha}} -f app/Dockerfile app

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        id: ecr-login

      - name: Push to ECR
        env:
          ECR_REGISTRY: ${{ steps.ecr-login.outputs.registry }}
        run: |
          docker tag ${{ env.ECR_REPOSITORY}}:${{github.sha}} \
            ${{ env.ECR_REGISTRY}}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}

          docker tag ${{ env.ECR_REPOSITORY}}:${{github.sha}} \
            ${{ env.ECR_REGISTRY}}/${{ env.ECR_REPOSITORY }}:latest

          docker push ${{ env.ECR_REGISTRY}}/${{ env.ECR_REPOSITORY}}:${{ github.sha }}
          docker push ${{ env.ECR_REGISTRY}}/${{ env.ECR_REPOSITORY}}:latest

          echo "### Image pushed :white_check_mark:" >> $GITHUB_STEP_SUMMARY
